# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

celdaCGcalcGibbsProbZ <- function(mCPbyS, nCPbyTS, nCP, L, alpha, beta) {
    .Call('_celda_celdaCGcalcGibbsProbZ', PACKAGE = 'celda', mCPbyS, nCPbyTS, nCP, L, alpha, beta)
}

celdaCGcalcGibbsProbY <- function(nCPbyTS, nByTS, nGbyTS, nGinY, beta, delta, gamma) {
    .Call('_celda_celdaCGcalcGibbsProbY', PACKAGE = 'celda', nCPbyTS, nByTS, nGbyTS, nGinY, beta, delta, gamma)
}

